### PR TITLE
Add disableHistory option (Fixes #44)

### LINKED ISSUE #44: option to disableHistory
sometimes I do not want the conversation (both message and response) to be recorded to history. I need an option to enable that.

    const resp = await ragChat.chat("Does the following sentence look like a question semantically? Say just yes or no " + question, {disableRAG: true, disableHistory: true});

### PR DESCRIPTION
**Pull request by eraykeskinmac**
This PR implements the `disableHistory` option for the RAGChat class as requested in issue #44. Here's what this PR includes:

- Added `disableHistory` option to `ChatOptions`
- Updated `RAGChat` class to handle the new option
- Implemented logic to skip history recording when `disableHistory` is set to true
- Added tests to verify the new functionality

This feature allows users to disable history recording for specific chat interactions, providing more flexibility in how chat history is managed.

Testing:
- Added unit tests for the new functionality
- Manually tested the feature to ensure it works as expected

Note: Some tests may fail due to missing environment variables. I've used the QStash token as suggested, but please let me know if any adjustments are needed.

### CODE REVIEW

**Comment by ogzhanolguncu** [comment]
@enesakar is this what you imaged? Let me know.

**Comment by enesakar** [comment]
cok tesekkurler @eraykeskinmac

**Comment by enesakar** [comment]
devamini bekleriz @eraykeskinmac

**Comment by eraykeskinmac** [comment]
@enesakar Çok teşekkürler abi! Devamı için çalışıyorum, projeyi inceledikçe daha fazlasını yapmak istiyorum.

**Review by ogzhanolguncu — APPROVED** [review]

**Comment by ogzhanolguncu** [comment]
@eraykeskinmac This is good, but I think we should also consider whether we want to fetch history from the store. @enesakar what do you think?

**Comment by enesakar** [comment]
when historyDisabled, the SDK should not call redis (to fetch history)

**Comment by ogzhanolguncu** [comment]
@eraykeskinmac  Addition to what we have right now, can you disable history fetch when `disableHistory` is active?

**Comment by eraykeskinmac** [comment]
@ogzhanolguncu  Sure i will add that feature to disable history fetch when disableHistory is active

**Comment by ogzhanolguncu** [comment]
@eraykeskinmac There were lots of conflicts I moved all your commits to https://github.com/upstash/rag-chat/pull/57 here. Your contributions are still there so nothing to worry about.

**Pull request closed without merging**
